Changxiang
Hello-World-Purdue/hw22-frontend pull request #3
Opened 2022-03-20 00:40 UTC by feindr54

2022-03-20 02:13 UTC, Hydrophobefireman requested changes

2022-03-20 02:13 UTC, Hydrophobefireman commented on pages/login.js
> +import './login.css'
could you convert this to either a css module (much preferred) or 
import it in _app.js instead?

our CI builds are failing because of this

2022-03-20 22:04 UTC, feindr54 commented on pages/login.js
> +import './login.css'
Got it, thanks for the suggestion!

2022-04-24 19:57 UTC, darreniyer0601 approved these changes

2022-04-24 19:59 UTC, darreniyer0601 commented on pages/login.js
> +import './login.css'
Imports converted to css module. Resolving this change request.

2022-04-24 21:34 UTC, closed without merging

2022-04-24 21:34 UTC, darreniyer0601 commented
Create new pull request once new changes are made. (Add package-lock.json to .gitignore)